# Generated by Django 4.0.4 on 2022-06-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_userfollows_following_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollows',
            old_name='following_user_id',
            new_name='following_user',
        ),
        migrations.RenameField(
            model_name='userfollows',
            old_name='user_id',
            new_name='user',
        ),
    ]
